"""
Known AI-generator and photo-editor self-tags.

When an AI tool (Midjourney, Stable Diffusion, Firefly, Topaz, ...) or a photo
editor (Photoshop, Snapseed, VSCO, ...) writes an image, it often leaves a small
label inside the file (EXIF / PNG-text / XMP). We match those labels to explain,
in plain language, WHY a file looks machine-made or edited.

This is a signal, never proof: a stripped file or a real camera photo carries
none of these tags, so absence does not mean "human-made".
"""

AI_SIGS = {
    "Midjourney": "the AI image generator Midjourney",
    "DALL-E": "OpenAI's AI image generator DALL-E",
    "OpenAI Images": "OpenAI's AI image generator",
    "Stable Diffusion": "the AI generator Stable Diffusion",
    "SDXL": "the AI model SDXL",
    "ComfyUI": "the AI workflow tool ComfyUI",
    "Adobe Firefly": "Adobe's AI generator Firefly",
    "Leonardo": "the AI generator Leonardo",
    "Ideogram": "the AI generator Ideogram",
    "Nano Banana": "the AI image model Nano Banana",
    "FLUX": "the AI image model FLUX",
    "Imagen": "Google's AI image generator Imagen",
    "Firefly": "Adobe's AI model Firefly",
    "Topaz": "the AI upscaler Topaz",
    "Topaz Photo AI": "the AI upscaler Topaz Photo AI",
    "Topaz Gigapixel": "the AI upscaler Topaz Gigapixel",
    "ESRGAN": "the AI upscaler ESRGAN",
    "Real-ESRGAN": "the AI upscaler Real-ESRGAN",
    "Magnific": "the AI upscaler Magnific",
    "Magnific.ai": "the AI upscaler Magnific",
    "Upscayl": "the AI upscaler Upscayl",
    "waifu2x": "the AI upscaler waifu2x",
    "img2go": "the AI tool img2go",
    "AI Enhance": "an AI photo enhancer",
    "Enhance AI": "an AI photo enhancer",
    "Neuro Night": "an AI upscaler (Neuro Night)",
    "RemoveBG": "the AI background-remover remove.bg",
    "Magic Resize": "Canva's AI upscaler (Magic Resize)",
    "Dream AI": "an AI image tool (Dream AI)",
    "Stable Diffusion XL": "the AI model SDXL",
    "Gemini": "Google's Gemini AI (image/text generator)",
    "Gemini Advanced": "Google's Gemini AI model",
    "Ideogram 3.0": "the AI generator Ideogram",
    "Recraft": "the AI generator Recraft",
    "Krea": "the AI generator Krea",
    "Runway": "the AI video/image generator Runway",
    "Runway Gen-3": "the AI generator Runway Gen-3",
    "Sora": "OpenAI's AI video generator Sora",
    "Veo": "Google's AI video model Veo",
    "Pika": "the AI video generator Pika",
    "Luma Dream Machine": "the AI video generator Luma Dream Machine",
    "Luma": "the AI video generator Luma",
    "Genie": "Google's AI image model Genie",
    "Stable Video": "the AI video model Stable Video",
    "FLUX (Tensor)": "the AI image model FLUX",
    "AnythingXL": "the AI image model AnythingXL",
    "AlbedoBase XL": "the AI image model AlbedoBase XL",
    "DreamShaper": "the AI image model DreamShaper",
    "Juggernaut XL": "the AI image model Juggernaut XL",
    "Kandinsky": "the AI image generator Kandinsky",
    "Wombo": "the AI image app Wombo Dream",
    "Hotpot": "the AI tool Hotpot.ai",
    "Fotor": "the AI photo editor Fotor (AI effects)",
    "Pixlr AI": "the AI editor Pixlr (AI features)",
    "Zyro": "the AI design tool Zyro (AI features)",
    "NightCafe": "the AI generator NightCafe",
    "DreamStudio": "the AI generator DreamStudio",
    "Playground Mod": "the AI generator Playground (Mod)",
    "DiffusionBee": "the AI generator DiffusionBee",
    "InvokeAI": "the AI generator InvokeAI",
    "Fooocus": "the AI generator Fooocus",
    "Artbreeder": "the AI face/id tool Artbreeder",
    "BigGAN": "the generative model BigGAN",
    "StyleGAN": "the generative model StyleGAN",
    "VQGAN": "the generative model VQGAN",
    "DALL-E 3": "OpenAI's AI image generator DALL-E 3",
    "Black Forest": "the AI studio Black Forest Labs (FLUX)",
}

EDITING_SIGS = {
    "Adobe Photoshop": "a graphic-design app (Adobe Photoshop)",
    "photoshop": "the photo-editor Adobe Photoshop",
    "Adobe ImageReady": "an image tool (Adobe ImageReady)",
    "Adobe Illustrator": "a vector-design app (Adobe Illustrator)",
    "GIMP": "a free photo-editor (GIMP)",
    "Canva": "the Canva design app",
    "Affinity": "Affinity (a design app)",
    "Pixelmator": "Pixelmator (a photo-editor)",
    "Inkscape": "Inkscape (a vector editor)",
    "Photopea": "Photopea (a browser photo-editor)",
    "Paint.NET": "Paint.NET (a photo-editor)",
    "Sketch": "the Sketch design app",
    "Figma": "the Figma design tool",
    "CorelDRAW": "the vector editor CorelDRAW",
    "Lightroom": "the photo-editor Adobe Lightroom",
    "PhotoDirector": "the photo-editor PhotoDirector",
    "PhotoScape": "the photo-editor PhotoScape",
    "PicMonkey": "the photo-editor PicMonkey",
    "BeFunky": "the photo-editor BeFunky",
    "PaintShop Pro": "the photo-editor PaintShop Pro",
    "Apple Preview": "the viewer Apple Preview",
    "Snapseed": "the photo-editor Snapseed",
    "PicsArt": "the photo-editor PicsArt",
    "VSCO": "the photo-editor VSCO",
    "Luminar": "the photo-editor Luminar",
    "Darkroom": "the photo-editor Darkroom",
    "RawTherapee": "the photo-editor RawTherapee",
    "darktable": "the photo-editor darktable",
    "Edits by Xara": "the design app Xara",
    "Autodesk Pixlr": "the photo-editor Pixlr",
    "ON1 Photo": "the photo-editor ON1",
    "Capture One": "the RAW editor Capture One",
    "Polish": "the photo-editor Polish",
    "Fotor": "the photo-editor Fotor",
}